### ISSUE TITLE
The process being executed does not receive the dbus-message

### ISSUE THREAD

**Issue by andsh** [jluttine/dbus-listen#1]
When the process is executed, it does not have the received dbus message neuther in environmet variables, nor in command line parameters. How to get the message to handle it?

**Comment by jluttine** [comment]
I'm sorry, I didn't understand. Could you give me the command you ran, expected output/behavior and actual output/behavior?

**Comment by jluttine** [comment]
Ah, now I understand, I was just a bit confused first, sorry about that. Indeed, it is not currently possible to get the actual message in the process. But I think it'd be a good idea to add such a feature. Not sure which one makes more sense: environment variables or command-line arguments. Probably environment variables at least by default so that it's easy to use commands that don't support such command-line arguments. Need to think what would be good environment variable names and what exactly to put there (that is, need to read a bit about the specs about the signal content).

**Comment by jluttine** [comment]
It seems that the body is a list of variants. A variant is typed value so it's basically a (type, value) pair. I wonder what would be the best format to forward this kind of content in environment variables. Perhaps JSON..? Not sure though.

A few links:

- Signal body is a list of variants: https://hackage.haskell.org/package/dbus-1.2.15.1/docs/DBus.html#v:signalBody
- Variant: https://hackage.haskell.org/package/dbus-1.2.15.1/docs/DBus.html#t:Variant

**Comment by andsh** [comment]
Hello
I have found a C implementation of the dbus API and I solved my task. 
I implemented my custom format of message representation into string to parce it by regecx more easy.
